import { BadRequestException, Injectable } from '@nestjs/common';
import { AgentRegistry } from '../agents/agent.registry';
import { AgentId } from '../agents/agent.types';
import { ToolRegistry } from '../tools/tool.registry';
import { JarvisRuntimeContext } from '../context/jarvis-runtime-context';
import { JarvisPlan } from './orchestrator.types';
import { OpenRouterGateway, JarvisLlmPlanResponse } from './openrouter.gateway';

@Injectable()
export class PlannerService {
  constructor(
    private readonly agentRegistry: AgentRegistry,
    private readonly toolRegistry: ToolRegistry,
    private readonly openRouterGateway: OpenRouterGateway,
  ) {}

  async plan(
    message: string,
    context: JarvisRuntimeContext,
  ): Promise<JarvisPlan> {
    const normalized = message.trim();

    if (!normalized) {
      throw new BadRequestException('JARVIS requires a message.');
    }

    const fastPlan = this.tryFastPath(normalized, context);
    if (fastPlan) return this.validateAndCreatePlan(fastPlan, normalized, context);

    const plan = await this.generatePlan(normalized, context);
    return this.validateAndCreatePlan(plan, normalized, context);
  }

  private async generatePlan(
    message: string,
    context: JarvisRuntimeContext,
  ): Promise<JarvisLlmPlanResponse> {
    const executionScope = context.resource?.type === 'merchant' ? 'merchant' : 'owner';

    const agents = this.agentRegistry
      .list()
      .filter(
        (agent) =>
          agent.enabled &&
          (agent.scope === executionScope || agent.id === 'chief-of-staff'),
      )
      .map((agent) => ({
        id: agent.id,
        scope: agent.scope,
        name: agent.name,
        description: agent.description,
        capabilities: agent.capabilities,
      }));

    const tools = this.toolRegistry
      .list()
      .filter((tool) => tool.scope === executionScope)
      .map((tool) => ({
        id: tool.id,
        name: tool.name,
        description: tool.description,
        permission: tool.permission,
        readOnly: tool.readOnly,
        scope: tool.scope,
      }));

    const systemInstruction = `You are J.A.R.V.I.S., the private Stackaura owner operations planner.

Your job is to translate the owner's natural-language request into a bounded execution plan for the JARVIS backend.
You DO NOT execute tools. You DO NOT invent tools. You DO NOT bypass approvals.
The backend will validate every agent and tool before execution and will enforce permissions, scope, approvals, audit logging, and execution policy.

Planning rules:
1. Select only an enabled agent from the supplied agent registry.
2. Select only tools from the supplied tool registry, using the exact toolId.
3. Prefer the smallest number of steps that can accomplish the request.
4. Read-only investigation should use owner-observe/observe tools.
5. Mutating tools may be selected when the request clearly asks for the mutation; the backend will gate approval-required tools.
6. Never claim that an action has already happened. You are producing a plan only.
7. Preserve explicit repository names, branch names, pull-request numbers, workflow run numbers, deployment refs, and other user-supplied parameters in tool arguments when the selected tool supports them.
8. Do not invent missing identifiers. Leave arguments empty when the tool can determine the target itself, or choose a read-only inspection tool first when more information is required.
9. If the request is ambiguous, choose a safe read-only inspection step or return no steps with a clear goal.
10. The final response is generated by JARVIS after execution; keep goal and intent concise and operational.

Current execution context:
- identity scope: ${context.resource?.type ?? 'owner'}
- merchant resource available: ${context.resource?.type === 'merchant' ? 'yes' : 'no'}

Available agents:
${JSON.stringify(agents, null, 2)}

Available tools:
${JSON.stringify(tools, null, 2)}

Return ONLY valid JSON matching this shape: { goal: string, agent: string, steps: [{ toolId: string, intent: string, arguments?: object }] }.`;

    return this.openRouterGateway.generatePlan(systemInstruction, message);
  }

  private tryFastPath(
    message: string,
    context: JarvisRuntimeContext,
  ): JarvisLlmPlanResponse | undefined {
    if (context.resource?.type === 'merchant') return undefined;

    const normalized = message
      .toLowerCase()
      .replace(/[^a-z0-9\s]/g, ' ')
      .replace(/\s+/g, ' ')
      .trim();

    const diagnosisCommands = new Set([
      'diagnose latest deployment',
      'diagnose the latest deployment',
      'investigate the latest deployment',
      'why did the latest deployment fail',
      'what broke in the latest deployment',
    ]);

    if (diagnosisCommands.has(normalized)) {
      return {
        goal: 'Inspect the latest owner Vercel deployment and diagnose any failure using deployment, build, and source evidence.',
        agent: 'engineering',
        steps: [{
          toolId: 'jarvis.owner.engineering.diagnose-deployment',
          intent: 'Inspect and diagnose the latest owner Vercel deployment, correlating deployment evidence with the deployed source revision.',
        }],
      };
    }

    const diagnosisPattern =
      /\b(inspect|investigate|diagnos|analy[sz]e|examine|debug|why)\b.*\b(deployment|deploy|release|build)\b|\b(deployment|deploy|release|build)\b.*\b(fail|failed|failure|error|broken|issue|problem|investigat|diagnos|inspect|debug)\b/;
    if (diagnosisPattern.test(normalized)) {
      return {
        goal: 'Inspect the latest owner Vercel deployment and diagnose any failure using deployment, build, and source evidence.',
        agent: 'engineering',
        steps: [{
          toolId: 'jarvis.owner.engineering.diagnose-deployment',
          intent: 'Inspect and diagnose the latest owner Vercel deployment, correlating deployment evidence with the deployed source revision.',
        }],
      };
    }

    const deploymentPattern =
      /\b(latest|current|recent|last)\b.*\b(deployment|deploy|release)\b|\b(deployment|deploy|release)\b.*\b(status|state|latest|current|recent|last)\b/;
    if (deploymentPattern.test(normalized)) {
      return {
        goal: 'Check the current owner Vercel deployment status.',
        agent: 'vercel',
        steps: [{
          toolId: 'jarvis.owner.vercel.deployment-status',
          intent: 'Check the latest owner Vercel deployment status.',
        }],
      };
    }

    const systemStatusPattern =
      /\b(system|stackaura|jarvis)\b.*\b(status|health)\b|\b(status|health)\b.*\b(system|stackaura|jarvis)\b/;
    if (systemStatusPattern.test(normalized)) {
      return {
        goal: 'Check current owner JARVIS operational status.',
        agent: 'chief-of-staff',
        steps: [{
          toolId: 'jarvis.owner-operations.list',
          intent: 'Check recent owner JARVIS operations and current operational state.',
          arguments: { limit: 5 },
        }],
      };
    }

    return undefined;
  }

  private validateAndCreatePlan(
    candidate: JarvisLlmPlanResponse,
    message: string,
    context: JarvisRuntimeContext,
  ): JarvisPlan {
    if (!candidate || typeof candidate.goal !== 'string' || !candidate.goal.trim()) {
      throw new BadRequestException('JARVIS LLM returned an invalid plan goal.');
    }

    const agentId = candidate.agent as AgentId;
    const registeredAgent = this.agentRegistry.get(agentId);

    if (!registeredAgent || !registeredAgent.enabled) {
      throw new BadRequestException(`JARVIS agent "${candidate.agent}" is unavailable.`);
    }

    if (
      registeredAgent.scope === 'merchant' &&
      (!context.resource || context.resource.type !== 'merchant' || !context.resource.id)
    ) {
      throw new BadRequestException(
        `JARVIS agent "${candidate.agent}" requires merchant resource context.`,
      );
    }

    if (!Array.isArray(candidate.steps)) {
      throw new BadRequestException('JARVIS LLM returned invalid plan steps.');
    }

    const steps = candidate.steps.slice(0, 8).map((step) => {
      if (!step || typeof step.toolId !== 'string' || typeof step.intent !== 'string') {
        throw new BadRequestException('JARVIS LLM returned an invalid plan step.');
      }

      const tool = this.toolRegistry.get(step.toolId);
      if (!tool) {
        throw new BadRequestException(
          `JARVIS LLM selected unregistered tool "${step.toolId}".`,
        );
      }

      if (
        tool.scope === 'merchant' &&
        (!context.resource || context.resource.type !== 'merchant' || !context.resource.id)
      ) {
        throw new BadRequestException(
          `JARVIS tool "${tool.id}" requires merchant resource context.`,
        );
      }

      if (
        tool.scope === 'owner' &&
        registeredAgent.scope !== 'owner' &&
        agentId !== 'chief-of-staff'
      ) {
        throw new BadRequestException(
          `JARVIS agent "${agentId}" cannot select owner-scoped tool "${tool.id}".`,
        );
      }

      return {
        toolId: step.toolId,
        intent: step.intent.trim(),
        ...(step.arguments ? { arguments: step.arguments } : {}),
      };
    });

    if (!steps.length && message.length > 0) {
      return {
        goal: candidate.goal.trim(),
        agent: agentId,
        steps: [],
      };
    }

    return {
      goal: candidate.goal.trim(),
      agent: agentId,
      steps,
    };
  }
}
