import { BadRequestException, Injectable, ServiceUnavailableException } from '@nestjs/common';
import { AgentRegistry } from '../agents/agent.registry';
import { AgentId } from '../agents/agent.types';
import { ToolRegistry } from '../tools/tool.registry';
import { JarvisRuntimeContext } from '../context/jarvis-runtime-context';
import { JarvisPlan } from './orchestrator.types';

const GEMINI_API_URL = 'https://generativelanguage.googleapis.com/v1beta/models';
const DEFAULT_MODEL = 'gemini-3.8-flash';
const DEFAULT_THINKING_LEVEL = 'medium';

type ThinkingLevel = 'low' | 'medium' | 'high';

interface GeminiPlanResponse {
  goal: string;
  agent: string;
  steps: Array<{
    toolId: string;
    intent: string;
    arguments?: Record<string, unknown>;
  }>;
}

@Injectable()
export class PlannerService {
  private readonly apiKey = process.env.GEMINI_API_KEY?.trim();
  private readonly model = process.env.GEMINI_MODEL?.trim() || DEFAULT_MODEL;
  private readonly thinkingLevel = this.parseThinkingLevel(
    process.env.GEMINI_THINKING_LEVEL?.trim() || DEFAULT_THINKING_LEVEL,
  );

  constructor(
    private readonly agentRegistry: AgentRegistry,
    private readonly toolRegistry: ToolRegistry,
  ) {}

  async plan(
    message: string,
    context: JarvisRuntimeContext,
  ): Promise<JarvisPlan> {
    const normalized = message.trim();

    if (!normalized) {
      throw new BadRequestException('JARVIS requires a message.');
    }

    if (!this.apiKey) {
      throw new ServiceUnavailableException(
        'JARVIS LLM is not configured. Set GEMINI_API_KEY on the JARVIS backend.',
      );
    }

    const plan = await this.generatePlan(normalized, context);
    return this.validateAndCreatePlan(plan, normalized, context);
  }

  private async generatePlan(
    message: string,
    context: JarvisRuntimeContext,
  ): Promise<GeminiPlanResponse> {
    const agents = this.agentRegistry
      .list()
      .filter((agent) => agent.enabled)
      .map((agent) => ({
        id: agent.id,
        scope: agent.scope,
        name: agent.name,
        description: agent.description,
        capabilities: agent.capabilities,
      }));

    const tools = this.toolRegistry.list().map((tool) => ({
      id: tool.id,
      name: tool.name,
      description: tool.description,
      permission: tool.permission,
      readOnly: tool.readOnly,
      scope: tool.scope,
    }));

    const systemInstruction = `You are J.A.R.V.I.S., the private Stackaura owner operations planner.

Your job is to translate the owner's natural-language request into a bounded execution plan for the JARVIS backend.
You DO NOT execute tools. You DO NOT invent tools. You DO NOT bypass approvals.
The backend will validate every agent and tool before execution and will enforce permissions, scope, approvals, audit logging, and execution policy.

Planning rules:
1. Select only an enabled agent from the supplied agent registry.
2. Select only tools from the supplied tool registry, using the exact toolId.
3. Prefer the smallest number of steps that can accomplish the request.
4. Read-only investigation should use owner-observe/observe tools.
5. Mutating tools may be selected when the request clearly asks for the mutation; the backend will gate approval-required tools.
6. Never claim that an action has already happened. You are producing a plan only.
7. Preserve explicit repository names, branch names, pull-request numbers, workflow run numbers, deployment refs, and other user-supplied parameters in tool arguments when the selected tool supports them.
8. Do not invent missing identifiers. Leave arguments empty when the tool can determine the target itself, or choose a read-only inspection tool first when more information is required.
9. If the request is ambiguous, choose a safe read-only inspection step or return no steps with a clear goal.
10. The final response is generated by JARVIS after execution; keep goal and intent concise and operational.

Current execution context:
- identity scope: ${context.resource?.type ?? 'owner'}
- merchant resource available: ${context.resource?.type === 'merchant' ? 'yes' : 'no'}

Available agents:
${JSON.stringify(agents, null, 2)}

Available tools:
${JSON.stringify(tools, null, 2)}

Return ONLY valid JSON matching this shape: { goal: string, agent: string, steps: [{ toolId: string, intent: string, arguments?: object }] }.`;

    const response = await fetch(
      `${GEMINI_API_URL}/${encodeURIComponent(this.model)}:generateContent`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-goog-api-key': this.apiKey!,
        },
        body: JSON.stringify({
          systemInstruction: {
            parts: [{ text: systemInstruction }],
          },
          contents: [
            {
              role: 'user',
              parts: [{ text: message }],
            },
          ],
          generationConfig: {
            thinkingConfig: {
              thinkingLevel: this.thinkingLevel,
            },
            responseMimeType: 'application/json',
          },
        }),
      },
    );

    if (!response.ok) {
      const detail = await response.text().catch(() => '');
      throw new ServiceUnavailableException(
        `JARVIS LLM request failed with status ${response.status}${detail ? `: ${detail.slice(0, 300)}` : '.'}`,
      );
    }

    const payload = (await response.json()) as {
      candidates?: Array<{
        content?: {
          parts?: Array<{ text?: string }>;
        };
      }>;
    };

    const text = payload.candidates?.[0]?.content?.parts
      ?.map((part) => part.text ?? '')
      .join('')
      .trim();

    if (!text) {
      throw new ServiceUnavailableException(
        'JARVIS LLM returned an empty planning response.',
      );
    }

    try {
      return JSON.parse(text) as GeminiPlanResponse;
    } catch {
      throw new ServiceUnavailableException(
        'JARVIS LLM returned an invalid planning response.',
      );
    }
  }

  private validateAndCreatePlan(
    candidate: GeminiPlanResponse,
    message: string,
    context: JarvisRuntimeContext,
  ): JarvisPlan {
    if (!candidate || typeof candidate.goal !== 'string' || !candidate.goal.trim()) {
      throw new BadRequestException('JARVIS LLM returned an invalid plan goal.');
    }

    const agentId = candidate.agent as AgentId;
    const registeredAgent = this.agentRegistry.get(agentId);

    if (!registeredAgent || !registeredAgent.enabled) {
      throw new BadRequestException(`JARVIS agent "${candidate.agent}" is unavailable.`);
    }

    if (
      registeredAgent.scope === 'merchant' &&
      (!context.resource || context.resource.type !== 'merchant' || !context.resource.id)
    ) {
      throw new BadRequestException(
        `JARVIS agent "${candidate.agent}" requires merchant resource context.`,
      );
    }

    if (!Array.isArray(candidate.steps)) {
      throw new BadRequestException('JARVIS LLM returned invalid plan steps.');
    }

    const steps = candidate.steps.slice(0, 8).map((step) => {
      if (!step || typeof step.toolId !== 'string' || typeof step.intent !== 'string') {
        throw new BadRequestException('JARVIS LLM returned an invalid plan step.');
      }

      const tool = this.toolRegistry.get(step.toolId);
      if (!tool) {
        throw new BadRequestException(
          `JARVIS LLM selected unregistered tool "${step.toolId}".`,
        );
      }

      if (tool.scope === 'merchant' && (!context.resource || context.resource.type !== 'merchant' || !context.resource.id)) {
        throw new BadRequestException(
          `JARVIS tool "${tool.id}" requires merchant resource context.`,
        );
      }

      if (tool.scope === 'owner' && registeredAgent.scope !== 'owner' && agentId !== 'chief-of-staff') {
        throw new BadRequestException(
          `JARVIS agent "${agentId}" cannot select owner-scoped tool "${tool.id}".`,
        );
      }

      return {
        toolId: step.toolId,
        intent: step.intent.trim(),
        ...(step.arguments ? { arguments: step.arguments } : {}),
      };
    });

    if (!steps.length && message.length > 0) {
      return {
        goal: candidate.goal.trim(),
        agent: agentId,
        steps: [],
      };
    }

    return {
      goal: candidate.goal.trim(),
      agent: agentId,
      steps,
    };
  }

  private parseThinkingLevel(value: string): ThinkingLevel {
    if (value === 'low' || value === 'high') return value;
    return 'medium';
  }
}
