import { Injectable } from '@nestjs/common';
import { JarvisTool } from './tool.types';

@Injectable()
export class ToolRegistry {
  private readonly tools: JarvisTool[] = [
    {
      id: 'jarvis.owner-operations.list',
      name: 'Owner Operation History',
      description: 'Read the authenticated owner’s JARVIS operation history.',
      permission: 'owner-observe',
      readOnly: true,
      scope: 'owner',
    },
    {
      id: 'jarvis.owner.vercel.deployment-status',
      name: 'Vercel Deployment Status',
      description: 'Read bounded status metadata for the latest owner Vercel deployment.',
      permission: 'owner-observe',
      readOnly: true,
      scope: 'owner',
    },
    {
      id: 'jarvis.owner.engineering.diagnose-deployment',
      name: 'Engineering Deployment Diagnosis',
      description: 'Diagnose the latest owner Vercel deployment using deployment metadata, build events, and GitHub commit correlation.',
      permission: 'owner-observe',
      readOnly: true,
      scope: 'owner',
    },
    {
      id: 'jarvis.owner.engineering.repair',
      name: 'Engineering Repair Workflow',
      description: 'Execute an owner-approved isolated source repair, verify GitHub CI, deploy the repaired revision, and verify the original failure is gone.',
      permission: 'approval',
      readOnly: false,
      scope: 'owner',
    },
    {
      id: 'jarvis.owner.vercel.deploy',
      name: 'Vercel Production Deployment',
      description: 'Deploy the selected owner Vercel project from an explicitly approved source.',
      permission: 'approval',
      readOnly: false,
      scope: 'owner',
    },
    {
      id: 'jarvis.owner.github.update-file',
      name: 'GitHub File Update',
      description: 'Replace an explicitly selected owner repository file with approved contents.',
      permission: 'approval',
      readOnly: false,
      scope: 'owner',
    },
    {
      id: 'jarvis.owner.github.create-branch',
      name: 'GitHub Branch Creation',
      description: 'Create an owner repository branch from an explicitly approved base reference.',
      permission: 'approval',
      readOnly: false,
      scope: 'owner',
    },
    {
      id: 'jarvis.owner.github.delete-branch',
      name: 'GitHub Branch Deletion',
      description: 'Delete an explicitly selected non-default owner repository branch after owner approval.',
      permission: 'approval',
      readOnly: false,
      scope: 'owner',
    },
    {
      id: 'jarvis.owner.github.merge-pull-request',
      name: 'GitHub Pull Request Merge',
      description: 'Merge an explicitly selected owner pull request after owner approval.',
      permission: 'approval',
      readOnly: false,
      scope: 'owner',
    },
    {
      id: 'jarvis.owner.github.rerun-workflow',
      name: 'GitHub Workflow Retry',
      description: 'Retry an explicitly selected failed GitHub Actions workflow job after owner approval.',
      permission: 'approval',
      readOnly: false,
      scope: 'owner',
    },
    {
      id: 'jarvis.owner.github.branch-inspect',
      name: 'GitHub Branch Inspection',
      description: 'Read the current commit and protection state of an explicitly selected owner repository branch.',
      permission: 'owner-observe',
      readOnly: true,
      scope: 'owner',
    },
    {
      id: 'jarvis.owner.github.file-inspect',
      name: 'GitHub File Inspection',
      description: 'Read an explicitly selected owner repository file at a branch or commit.',
      permission: 'owner-observe',
      readOnly: true,
      scope: 'owner',
    },
    {
      id: 'jarvis.owner.github.commit-inspect',
      name: 'GitHub Commit Inspection',
      description: 'Inspect an owner repository commit and its changed files for engineering diagnosis.',
      permission: 'owner-observe',
      readOnly: true,
      scope: 'owner',
    },
    {
      id: 'jarvis.owner.github.compare',
      name: 'GitHub Revision Comparison',
      description: 'Compare two owner repository revisions and return bounded file-level change metadata.',
      permission: 'owner-observe',
      readOnly: true,
      scope: 'owner',
    },
    {
      id: 'jarvis.owner.github.pull-request-inspect',
      name: 'GitHub Pull Request Inspection',
      description: 'Inspect an owner repository pull request and its current merge state.',
      permission: 'owner-observe',
      readOnly: true,
      scope: 'owner',
    },
    {
      id: 'jarvis.owner.github.workflow-inspect',
      name: 'GitHub Workflow Inspection',
      description: 'Inspect an owner repository GitHub Actions workflow run.',
      permission: 'owner-observe',
      readOnly: true,
      scope: 'owner',
    },
    {
      id: 'jarvis.owner.github.create-pull-request',
      name: 'GitHub Pull Request Creation',
      description: 'Create an explicitly approved pull request from an owner repository branch.',
      permission: 'approval',
      readOnly: false,
      scope: 'owner',
    },
    {
      id: 'jarvis.owner.github.close-pull-request',
      name: 'GitHub Pull Request Closure',
      description: 'Close an explicitly selected owner pull request after owner approval.',
      permission: 'approval',
      readOnly: false,
      scope: 'owner',
    },
    {
      id: 'jarvis.owner.github.repository-status',
      name: 'GitHub Repository Status',
      description:
        'Read bounded status metadata for an explicitly selected owner repository.',
      permission: 'owner-observe',
      readOnly: true,
      scope: 'owner',
    },
    {
      id: 'jarvis.approval-test',
      name: 'JARVIS Approval Test',
      description:
        'Harmless approval-gated tool used to verify the JARVIS authorization workflow.',
      permission: 'approval',
      readOnly: true,
      scope: 'merchant',
    },
    {
      id: 'command-center.overview',
      name: 'Command Center Overview',
      description: 'Read the current Stackaura operational overview.',
      permission: 'observe',
      readOnly: true,
      scope: 'merchant',
    },
    {
      id: 'payments.status',
      name: 'Payments Status',
      description: 'Read real payment, gateway-attempt and webhook health metrics for the merchant over a bounded time window.',
      permission: 'observe',
      readOnly: true,
      scope: 'merchant',
    },
    {
      id: 'payments.failures',
      name: 'Payment Failures',
      description: 'Read recent failed payments and failure concentration by gateway for the merchant.',
      permission: 'observe',
      readOnly: true,
      scope: 'merchant',
    },
    {
      id: 'payments.recent',
      name: 'Recent Payments',
      description: 'Read the most recent Stackaura payments directly from the payment data source.',
      permission: 'observe',
      readOnly: true,
      scope: 'merchant',
    },
    {
      id: 'payments.gateway-health',
      name: 'Gateway Health',
      description: 'Read payment gateway activity and health metrics.',
      permission: 'observe',
      readOnly: true,
      scope: 'merchant',
    },
    {
      id: 'payments.webhook-health',
      name: 'Webhook Health',
      description: 'Read webhook delivery health and success metrics.',
      permission: 'observe',
      readOnly: true,
      scope: 'merchant',
    },
    {
      id: 'finance.revenue-summary',
      name: 'Revenue Summary',
      description: 'Read the current Stackaura revenue and payment summary.',
      permission: 'observe',
      readOnly: true,
      scope: 'merchant',
    },
  ];

  get(toolId: string): JarvisTool | undefined {
    return this.tools.find((tool) => tool.id === toolId);
  }

  list(): JarvisTool[] {
    return [...this.tools];
  }
}
